name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
         6.0.x
         8.0.x

    - name: Install Playwright CLI
      run: dotnet tool install --global Microsoft.Playwright.CLI
    - name: Build playwright driver
      run: dotnet build PresrvicaExercise/UiSignUpTest.csproj --configuration Release
    - name: Install PowerShell
      run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell
   
    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool
    - name: Build playwright driver
      run: dotnet build PresrvicaExercise/UiSignUpTest.csproj --configuration Release
    - name: Ensure browsers are installed
      run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
    - name: Build playwright driver
      run: dotnet test PresrvicaExercise/UiSignUpTest.csproj --configuration Release
    
    - name: Restore dependencies for RestAPi Project
      run: dotnet restore RestAPiProject/RestAPiProject.csproj
    - name:  Build RestAPi Project
      run: dotnet build RestAPiProject/RestAPiProject.csproj --configuration Release
    - name: 🧪 Run REST API Tests
      run: dotnet test RestAPiProject/RestAPiProject.csproj --configuration Release --logger "trx;LogFileName=TestResults/api-results.trx"

   
    - name: Generate HTML test report
      run: |
        reportgenerator \
          -reports:**/TestResults/*.trx \
          -targetdir:TestResults/Report \
          -reporttypes:Html

    - name: Upload HTML report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: TestReport
        path: TestResults/Report
